name: ci-cd-databricks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install project dependencies
        run: uv sync --all-extras --dev

      - name: Run pytest (unit only)
        run:  uv run pytest -q -m "not integration" || ([ $? -eq 5 ] && echo "No unit tests found, skipping" && exit 0)


      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main
      
      - name: Create Databricks CLI profiles
        run: |
          cat > ~/.databrickscfg <<EOF
          [DEFAULT]
          host = ${DATABRICKS_HOST}
          azure_tenant_id = ${ARM_TENANT_ID}
          azure_client_id = ${ARM_CLIENT_ID}
          azure_client_secret = ${ARM_CLIENT_SECRET}

          [prod-sp]
          host = ${DATABRICKS_HOST}
          azure_tenant_id = ${ARM_TENANT_ID}
          azure_client_id = ${ARM_CLIENT_ID}
          azure_client_secret = ${ARM_CLIENT_SECRET}
          EOF


      - name: Validate bundle (ci)
        run: databricks bundle validate -t ci

      - name: Validate bundle (prod)
        run: databricks bundle validate -t prod

      
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: ci-checks
    runs-on: ubuntu-latest
    environment: prod
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main
      
      - name: Create Databricks CLI profiles
        run: |
          cat > ~/.databrickscfg <<EOF
          [DEFAULT]
          host = ${DATABRICKS_HOST}
          azure_tenant_id = ${ARM_TENANT_ID}
          azure_client_id = ${ARM_CLIENT_ID}
          azure_client_secret = ${ARM_CLIENT_SECRET}

          [prod-sp]
          host = ${DATABRICKS_HOST}
          azure_tenant_id = ${ARM_TENANT_ID}
          azure_client_id = ${ARM_CLIENT_ID}
          azure_client_secret = ${ARM_CLIENT_SECRET}
          EOF

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
      
      - name: Deploy bundle (prod)
        run: databricks bundle deploy -t prod
